version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: stock-analysis-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: stock-analysis-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8000
    restart: unless-stopped